"""add status column to todos

Revision ID: 77e442eaec8a
Revises: 3fe61ef2fdc5
Create Date: 2025-11-09 01:20:16.875707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e442eaec8a'
down_revision: Union[str, Sequence[str], None] = '3fe61ef2fdc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'status')
    # ### end Alembic commands ###